#!/usr/bin/bash

GATEWAY="https://gateway.ipfs.io/ipfs"

path="$1"

if [[ "${path:0:7}" = "http://" || \
      "${path:0:8}" = "https://" || \
      "${path:0:6}" = "ftp://" ]]
then
    file=$(mktemp "/tmp/ipin.XXX")
    wget -q -O "${file}" "${path}"
else
    if [ -e "${path}" ]
    then
	    file="${path}"
    else # hash
	    hashstr="${path}"
    fi
fi

if [ -z "${file}" ]
then
ipfs pin add ${hashstr}
else
file="${file}"
ipfsout=$(ipfs add "${file}")

filehash=$(echo "${ipfsout}" |  cut -d' ' -f2)

echo $GATEWAY/${filehash}
fi
