#!/usr/bin/bash

GATEWAY="https://gateway.ipfs.io/ipfs"
IPFS_USER=ipfs
IPFS_GROUP=ipfs
SUDO="sudo -u $IPFS_USER"

path="$1"

if [[ "${path:0:7}" = "http://" || \
      "${path:0:8}" = "https://" || \
      "${path:0:6}" = "ftp://" ]]
then
    file=$(mktemp "/tmp/ipin.XXX")
    wget -q -O "${file}" "${path}"
else
    if [ -e "${path}" ]
    then
	    file="${path}"
    else # hash
	    hashstr="${path}"
    fi
fi

if [ -z "${file}" ]
then
	$SUDO ipfs pin add ${hashstr}
else
	filename=$(basename ${file})

	if $SUDO bash -c "[ ! -r "${file}" ]"
	then
		if ! groups | grep -q $IPFS_GROUP
		then
			# because we want to do a chgrp
			>&2 echo "error: user must belong to group $IPFS_GROUP"
			exit 1
		fi

		tmpdir=$(mktemp -d "/tmp/ipin.XXX")
		cp -a "${file}" "${tmpdir}"
		chmod g+rx ${tmpdir}
		chmod g+r ${tmpdir}/${filename}
		chgrp $IPFS_GROUP ${tmpdir} ${tmpdir}/${filename}
		fileadd="${tmpdir}/${filename}"
	else
		fileadd=${file}
	fi
	ipfsout=$($SUDO ipfs add -w "${fileadd}")

	dirhash=$(echo "${ipfsout}" | sed -n '$p' | cut -d' ' -f2)

	echo $GATEWAY/${dirhash}/${filename}
fi
